baseURL: https://example.com
languageCode: sv-se
defaultContentLanguage: sv
title: Proust projektet
theme: cupper-hugo-theme
googleAnalytics: UA-123456789-1
enableGitInfo: true

# taxonomies:
#   tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: 
  homeMetaContent: Min läsning av På spaning efter den tid som flytt.
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: 2006-01-02
  katex: true
  hideHeaderLinks: false
  search: false
  showThemeSwitcher: false
  defaultDarkTheme: false
  moveFooterToHeader: false
  # navTitleText: Cupper Theme
  logoAlt: Min läsning av På spaning efter den tid som flytt.
  customCss:
    - css/custom_01.css
    - css/custom_02.css
  customJs:
    - js/custom_01.js
    - js/custom_02.js

menu:
  nav:
    - name: Proustprojektet
      url: /
      weight: 1
    - name: Swanns värld
      url: /swann/
      weight: 2
    - name: Proust och jag
      url: /proustOchJag
      weight: 3
    # - name: Om mig
    #   url: /omMig
    #   weight: 4

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2